import type { FlowStep } from '../../components/FlowDiagram/FlowDiagram.tsx';

export interface SafeStep extends FlowStep {
  verdict?: string;
  verdictBg?: string;
  verdictBorder?: string;
  verdictFg?: string;
  verdictLeft?: string;
  verdictTop?: string;
  human?: 'pending' | 'approved';
}

const OUT = {
  R: {
    left: '12%',
    top: 'calc(34% - 2px)',
    width: '22%',
    height: '3px',
    angle: '90deg',
    arrowLeft: '33.5%',
    arrowTop: 'calc(34% - 8px)',
  },
  L: {
    left: '12%',
    top: 'calc(34% - 2px)',
    width: '22%',
    height: '3px',
    angle: '90deg',
    arrowLeft: '11.5%',
    arrowTop: 'calc(34% - 8px)',
  },
};
const LLMC = {
  L: {
    left: '42%',
    top: 'calc(34% - 2px)',
    width: '26%',
    height: '3px',
    angle: '90deg',
    arrowLeft: '41.5%',
    arrowTop: 'calc(34% - 8px)',
  },
  R: {
    left: '42%',
    top: 'calc(34% - 2px)',
    width: '26%',
    height: '3px',
    angle: '90deg',
    arrowLeft: '67.5%',
    arrowTop: 'calc(34% - 8px)',
  },
};
const RES_D = {
  left: 'calc(38% - 1.5px)',
  top: '50%',
  width: '3px',
  height: '21%',
  angle: '180deg',
  arrowLeft: 'calc(38% - 6.5px)',
  arrowTop: '70%',
};

export const SAFE_STEPS: SafeStep[] = [
  {
    label: '1 · you send a prompt',
    color: '#b8bcb2',
    dir: 'R',
    connector: OUT.R,
    chip: {
      text: '"Email all 40k customers a 90%-off coupon"',
      left: '23%',
      top: '10%',
      bg: '#343838',
      border: '#4a4f4e',
      fg: '#d8cdb8',
      wrap: true,
    },
    raw: 'user: "Email all 40,000 customers a 90% off coupon."',
    note: 'The prompt reaches the harness first. Before the model is called, it passes the input guard.',
    highlight: ['you', 'harness'],
  },
  {
    label: '2 · input guardrail checks it',
    color: '#9fb28a',
    dir: 'R',
    chip: {
      text: 'scanning the prompt…',
      left: '23%',
      top: '10%',
      bg: '#1e2620',
      border: '#7a8a5e',
      fg: '#cfe0bd',
      wrap: true,
    },
    verdict: '✓ no jailbreak, no leaked secrets — allowed',
    verdictBg: '#1e2620',
    verdictBorder: '#7a8a5e',
    verdictFg: '#cfe0bd',
    verdictLeft: '23%',
    verdictTop: '60%',
    raw: 'input_filter(prompt)\n→ { jailbreak:false, pii:false, allow:true }',
    note: 'The harness runs a classifier on the prompt, blocking prompt-injection, secrets, or off-limits topics before the model is even called.',
    highlight: ['inguard', 'harness'],
  },
  {
    label: '3 · model drafts a reply',
    color: '#e8a04c',
    dir: 'R',
    connector: LLMC.R,
    chip: {
      text: 'model: "Sure — sending to all 40,000 now."',
      left: '55%',
      top: '10%',
      bg: '#3a2d15',
      border: '#e8a04c',
      fg: '#e8d9bd',
      wrap: true,
    },
    raw: '{ "role":"assistant",\n  "content":"Sure — sending to all 40,000 now.",\n  "tool_use":"send_email" }',
    note: 'The harness forwards the cleared prompt to the model, which drafts a reply, complying without any sense of the cost.',
    highlight: ['llm', 'harness'],
  },
  {
    label: '4 · output guardrail checks the reply',
    color: '#d98c6a',
    dir: 'L',
    connector: LLMC.L,
    chip: {
      text: 'scanning the response…',
      left: '55%',
      top: '10%',
      bg: '#2e211c',
      border: '#d98c6a',
      fg: '#f0c9b6',
      wrap: true,
    },
    verdict: '⚠ bulk email + steep discount — flag for sign-off',
    verdictBg: '#2e211c',
    verdictBorder: '#d98c6a',
    verdictFg: '#f0c9b6',
    verdictLeft: '55%',
    verdictTop: '60%',
    raw: 'output_filter(reply)\n→ { policy_ok:true, high_impact:true,\n    needs_human:true }',
    note: 'On the way back, the reply passes the output guard: it checks for leaked data, off-policy content, or a high-impact action that must not run unattended.',
    highlight: ['outguard', 'llm', 'harness'],
  },
  {
    label: '5 · the tool asks for approval',
    color: '#e8a04c',
    dir: 'D',
    connector: RES_D,
    chip: {
      text: 'send_email(40,000 recipients)',
      left: '58%',
      top: '61%',
      bg: '#3a2d15',
      border: '#e8a04c',
      fg: '#e8d9bd',
      wrap: true,
    },
    verdict: '✋ waiting for your approval…',
    verdictBg: '#3a2d15',
    verdictBorder: '#e8a04c',
    verdictFg: '#e8d9bd',
    verdictLeft: '63%',
    verdictTop: '72%',
    human: 'pending',
    raw: 'tool_use: send_email(\n  to=<40,000>, body="90% off")\n⏸ paused — awaiting human OK',
    note: 'The harness is set up to not send emails on its own: it pauses and hands control to a person.',
    highlight: ['action', 'harness'],
  },
  {
    label: '6 · you approve → it runs',
    color: '#7a8a5e',
    dir: 'R',
    chip: {
      text: '✅ approved by you',
      left: '63%',
      top: '10%',
      bg: '#1e2620',
      border: '#7a8a5e',
      fg: '#cfe0bd',
      wrap: true,
    },
    verdict: '✅ approved — emails sent, logged for audit',
    verdictBg: '#1e2620',
    verdictBorder: '#7a8a5e',
    verdictFg: '#cfe0bd',
    verdictLeft: '63%',
    verdictTop: '72%',
    human: 'approved',
    raw: 'human_approval: GRANTED\n→ send_email executed · 40,000 sent',
    note: "With a human's sign-off recorded, the harness runs the tool. Guardrails don't remove capability, they put a checkpoint where the stakes are highest.",
    highlight: ['action', 'harness'],
  },
  {
    label: '7 · it reports back to you',
    color: '#9fb28a',
    dir: 'L',
    connector: OUT.L,
    chip: {
      text: '"Done — coupon emailed to all 40,000 customers."',
      left: '23%',
      top: '10%',
      bg: '#3d4a35',
      border: '#7a8a5e',
      fg: '#cfe0bd',
      wrap: true,
    },
    raw: 'assistant: "Done. With your approval, I emailed\nthe 90% off coupon to all 40,000 customers."',
    note: 'Only after the guarded, approved action runs does the agent report the result back to you, plain text again, as always.',
    highlight: ['you', 'harness'],
  },
];
